# target group configuration -> creates the target group and target type
# TargetGroupConfiguration (05-tg.yaml): Defines how a target group should behave (e.g., targetType: ip, health check path) if created for a
 # service, but it does not create one on its own.
apiVersion: gateway.k8s.aws/v1
kind: TargetGroupConfiguration
metadata:
  name: app1
  namespace: roboshop
spec:
  targetReference:
    name: app1
    kind: Service
  defaultConfiguration:
    targetType: ip